language: node_js
node_js:
  - '0.10'
notifications:
  email: false
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-egress' ]; then cd .. && eval "mv $currentfolder generator-egress" && cd generator-egress; fi